server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: user
          uri: http://localhost:8082
          predicates:
            - Path=/users/**, /userReadModels/**
        - id: auth 
          uri: http://localhost:8083
          predicates:
            - Path=/auths/**, /authReadModels/**
        - id: board
          uri: http://localhost:8084
          predicates:
            - Path=/boards/**, /boardReadModels/**
        - id: report
          uri: http://localhost:8085
          predicates:
            - Path=/reports/**, /reportReadModels/**
        - id: api gateway
          uri: http://localhost:8086
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/users/**, 
        - id: auth 
          uri: http://auth:8080
          predicates:
            - Path=/auths/**, 
        - id: board
          uri: http://board:8080
          predicates:
            - Path=/boards/**, 
        - id: report
          uri: http://report:8080
          predicates:
            - Path=/reports/**, 
        - id: api gateway
          uri: http://apiGateway:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
